# Generated by Django 4.2.3 on 2023-10-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_like_users'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_articles',
            field=models.ManyToManyField(related_name='like_users', to='articles.article'),
        ),
    ]
