# Generated by Django 4.2.3 on 2023-10-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_like_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_articles',
        ),
    ]
